/*
  Title:     ASD Low-Level Table Format
  Status:    C Library Extension
  Copyright: (C) 1991, Advanced RISC Machines Ltd., Cambridge, England.
*/
/*
 * RCS $Revision: 1.4 $
 * Checkin $Date: 1994/12/15 17:39:25 $
 * Revising $Author: enevill $
 */

/*
 * This header file describes low-level debugging structures used by ASD.
 * These are generated by the linker if the -debug option is set.
 */

#ifndef __asdll_h
#define __asdll_h

/* defines for flags field in struct asd_sym */

#define ASD_LOCSYM      0
#define ASD_GLOBSYM     0x01000000
#define ASD_LOCGLOBMASK 0x01000000

#define ASD_ABSSYM      0
#define ASD_TEXTSYM     0x02000000
#define ASD_DATASYM     0x04000000
#define ASD_ZINITSYM    0x06000000
#define ASD_HISTMASK    0x06000000

#define ASD_16BITSYM    0x10000000

#ifndef unsigned32
#  define unsigned32 unsigned long
#endif

struct asd_sym {
    unsigned32 flags;  /* actually stridx in the ls 24 bits */
                       /* flags in the high-order 8 bits    */
    unsigned32 value;
};

#define ITEMSECTION     1

struct asd_section {
    unsigned   itemcode:16;
    unsigned   length:16;
#ifdef __ZTC__
    unsigned32 language:24;
    unsigned32 debugversion:8;
#else
    unsigned   language:24;
    unsigned   debugversion:8;
#endif
    unsigned32 codeaddr;
    unsigned32 dataaddr;
    unsigned32 codesize;
    unsigned32 datasize;
    unsigned32 fileinfo;
    unsigned32 debugsize;
    unsigned32 nsyms;
};

#endif
